import { courseCardImages } from "@/constants/constants";
import { Course } from "@/types/type";

export const dummyCourses: Course[] = [
  {
    imgSrc: courseCardImages[0],
    imgAlt: "Modern JavaScript course",
    heading: "Modern JavaScript From Beginner to Advanced",
    authorName: "Sarah Mitchell",
    rating: "4.8",
  },
  {
    imgSrc: courseCardImages[1],
    imgAlt: "React development course",
    heading: "React.js: Build Modern Web Applications",
    authorName: "Alex Johnson",
    rating: "4.9",
  },
  {
    imgSrc: courseCardImages[2],
    imgAlt: "Next.js course",
    heading: "Next.js 16 Full-Stack Development",
    authorName: "Daniel Carter",
    rating: "4.7",
  },
  {
    imgSrc: courseCardImages[3],
    imgAlt: "TypeScript programming course",
    heading: "TypeScript for Professional Developers",
    authorName: "Emily Anderson",
    rating: "4.8",
  },
  {
    imgSrc: courseCardImages[4],
    imgAlt: "UI UX design course",
    heading: "UI/UX Design Fundamentals",
    authorName: "Michael Brown",
    rating: "4.6",
  },
  {
    imgSrc: courseCardImages[5],
    imgAlt: "Tailwind CSS course",
    heading: "Master Tailwind CSS From Scratch",
    authorName: "Sophia Williams",
    rating: "4.9",
  },
  {
    imgSrc: courseCardImages[0],
    imgAlt: "Node.js backend course",
    heading: "Node.js Backend Development",
    authorName: "James Wilson",
    rating: "4.7",
  },
  {
    imgSrc: courseCardImages[1],
    imgAlt: "Full stack development course",
    heading: "Full-Stack Web Development Bootcamp",
    authorName: "Olivia Martin",
    rating: "4.9",
  },
  {
    imgSrc: courseCardImages[2],
    imgAlt: "Git and GitHub course",
    heading: "Git & GitHub for Modern Developers",
    authorName: "William Davis",
    rating: "4.6",
  },
  {
    imgSrc: courseCardImages[3],
    imgAlt: "Figma design course",
    heading: "Figma for Web Designers",
    authorName: "Emma Thompson",
    rating: "4.8",
  },
  {
    imgSrc: courseCardImages[4],
    imgAlt: "Python programming course",
    heading: "Python Programming for Beginners",
    authorName: "Noah Taylor",
    rating: "4.7",
  },
  {
    imgSrc: courseCardImages[5],
    imgAlt: "Artificial intelligence course",
    heading: "Introduction to Artificial Intelligence",
    authorName: "Sophia Clark",
    rating: "4.9",
  },
  {
    imgSrc: courseCardImages[0],
    imgAlt: "Database development course",
    heading: "SQL & Database Design Essentials",
    authorName: "Liam Anderson",
    rating: "4.5",
  },
  {
    imgSrc: courseCardImages[1],
    imgAlt: "API development course",
    heading: "REST API Development With Node.js",
    authorName: "Mia Rodriguez",
    rating: "4.8",
  },
  {
    imgSrc: courseCardImages[2],
    imgAlt: "Frontend development course",
    heading: "Advanced Frontend Engineering",
    authorName: "Ethan Thomas",
    rating: "4.9",
  },
  {
    imgSrc: courseCardImages[3],
    imgAlt: "CSS animation course",
    heading: "CSS Animations & Creative Web Design",
    authorName: "Ava Martinez",
    rating: "4.6",
  },
  {
    imgSrc: courseCardImages[4],
    imgAlt: "React Native course",
    heading: "React Native Mobile App Development",
    authorName: "Lucas Garcia",
    rating: "4.8",
  },
  {
    imgSrc: courseCardImages[5],
    imgAlt: "Web performance course",
    heading: "Web Performance Optimization",
    authorName: "Isabella Moore",
    rating: "4.7",
  },
  {
    imgSrc: courseCardImages[0],
    imgAlt: "Software architecture course",
    heading: "Software Architecture for Developers",
    authorName: "Benjamin Lee",
    rating: "4.9",
  },
  {
    imgSrc: courseCardImages[1],
    imgAlt: "AI engineering course",
    heading: "AI Engineering for Web Developers",
    authorName: "Charlotte Walker",
    rating: "4.8",
  },
];
